version: "3"
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      HTTPS_METHOD: noredirect
      DEFAULT_HOST: ${DOMAIN}
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx
      DEFAULT_EMAIL: admin@${DOMAIN}

  trojan:
    image: trojangfw/trojan
    container_name: trojan
    restart: always
    external_links:
      - nginx
    ports:
      - 443:443
    volumes:
      - ../trojan.json:/config/config.json
      - ../certs/${DOMAIN}:/certs

  VLESS:
    image: v2fly/v2fly-core:v4.32.0
    container_name: VLESS
    restart: always
    ports:
      - 3743:443
    external_links:
      - nginx
    volumes:
      - ../VLESS.json:/etc/v2ray/config.json
      - ../certs/${DOMAIN}:/certs
    environment:
      DOMAIN: ${DOMAIN}
    command: v2ray -config=/etc/v2ray/config.json

  vless2:
    image: charlieethan/vless
    container_name: vless2
    restart: always
    ports:
      - 3744:443
    external_links:
      - nginx
    volumes:
      - ./VLESS.json:/etc/v2ray/config.json
      - ./certs/${DOMAIN}:/certs
    environment:
      DOMAIN: ${DOMAIN}
    command: v2ray -config=/etc/v2ray/config.json