version: "3"

services:

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis

  composer:
    image: prooph/composer:7.1
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: install

  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    volumes:
      - ./public:/var/www/public
    ports:
      - 80:80

  db:
    image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=larabbs
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret

  redis:
    image: redis:5