version: '3.3'

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    # environment:
    #   DEFAULT_HOST: hailu.org

  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx
      DEFAULT_EMAIL: app@lxooo.com

  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql
  #   restart: always
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   ports:
  #     - 3721:3306
  #   environment:
  #     - "MYSQL_ROOT_PASSWORD=Google123!@#"
  #     - "MYSQL_USER=google"
  #     - "MYSQL_PASSWORD=Google123123"

  # frp:
  #   image: fatedier/frp
  #   container_name: frp
  #   restart: always
  #   volumes:
  #     - ./frp/frps.ini:/frps.ini
  #   expose:
  #     - 443
  #   ports:
  #     - 808:808
  #     - 7000:7000
  #   environment:
  #     VIRTUAL_HOST: esxi.hailu.org,ros.hailu.org,openwrt.hailu.org
  #     LETSENCRYPT_HOST: hailu.org,esxi.hailu.org,ros.hailu.org,openwrt.hailu.org
  #     HTTPS_METHOD: noredirect

  wordpress:
    image: wordpress:php7.2-fpm-alpine
    container_name: wordpress
    restart: always
    volumes:
      - ./bot.lxooo.com:/bot.lxooo.com
      - ./hailu.org:/hailu.org
      - ./lxooo.com:/var/www/html
      - ./wordpress/php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  lxooo:
    image: nginx:alpine
    container_name: lxooo
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./lxooo.com:/var/www/html
      - ./wordpress/lxooo.com.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: lxooo.com,www.lxooo.com,t.lxooo.com
      # LETSENCRYPT_HOST: lxooo.com,www.lxooo.com,t.lxooo.com
      # HTTPS_METHOD: noredirectls

  bot:
    image: nginx:alpine
    container_name: bot
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./bot.lxooo.com:/bot.lxooo.com
      - ./wordpress/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: bot.lxooo.com
      # LETSENCRYPT_HOST: lxooo.com,bot.lxooo.com
      # HTTPS_METHOD: noredirect

  hailu:
    image: nginx:alpine
    container_name: hailu
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./hailu.org:/hailu.org
      - ./wordpress/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: hailu.org
      # LETSENCRYPT_HOST: hailu.org
      # HTTPS_METHOD: noredirect

  oa:
    image: nginx:alpine
    container_name: oa
    restart: always
    volumes:
      - ./oa.sungmee.com:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: oa.sungmee.com
      # LETSENCRYPT_HOST: oa.sungmee.com
      # HTTPS_METHOD: noredirect

  api:
    image: sungmee/hyperlara
    container_name: api
    restart: always
    volumes:
      - ./oa.hailu.org:/var/www
    environment:
      VIRTUAL_HOST: oa.hailu.org
      # LETSENCRYPT_HOST: hailu.org,oa.hailu.org
      # HTTPS_METHOD: noredirect

  ea:
    image: sungmee/hyperlara
    container_name: ea
    restart: always
    volumes:
      - ./ea.soofx.com:/var/www
    environment:
      VIRTUAL_HOST: ea.soofx.com
      # LETSENCRYPT_HOST: ea.soofx.com
      # HTTPS_METHOD: noredirect

  dway:
    image: sungmee/hyperlara
    container_name: dway
    restart: always
    volumes:
      - ./dway.lxooo.com:/var/www
    environment:
      VIRTUAL_HOST: dway.lxooo.com
      # LETSENCRYPT_HOST: lxooo.com,dway.lxooo.com
      # HTTPS_METHOD: noredirect