version: "3"

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - ${HTTPS_PORT:-444}:443
    volumes:
      - ../nginx/vhost.d:/etc/nginx/vhost.d
      - ../nginx/html:/usr/share/nginx/html
      - ../certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - ../nginx/vhost.d:/etc/nginx/vhost.d
      - ../nginx/html:/usr/share/nginx/html
      - ../certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx
      DEFAULT_EMAIL: admin@${DOMAIN}

  ftp:
    image: fauria/vsftpd
    container_name: ftp
    restart: always
    volumes:
      - ./public:/home/vsftpd
    ports:
      - "3720:21"
      - 3789-3799:3789-3799
    environment:
      FTP_USER: ftp
      FTP_PASS: ftp123
      PASV_ADDRESS: ${PASV_ADDRESS:-127.0.0.1}
      PASV_MIN_PORT: 3789
      PASV_MAX_PORT: 3799
      LOCAL_UMASK: 0
      FILE_OPEN_MODE: 0664
      ANON_UMASK: 0664
      VIRTUAL_HOST: ftp.${DOMAIN}