version: '3'

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    # network_mode: bridge

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx
    # network_mode: bridge

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD"
      - "MYSQL_DATABASE=MYSQL_DATABASE"
      - "MYSQL_USER=MYSQL_USER"
      - "MYSQL_PASSWORD=MYSQL_PASSWORD"

  app:
    image: sungmee/hyperlara
    container_name: app
    restart: always
    volumes:
      - ./app:/var/www
    links:
      - redis
      - db
    depends_on:
      - nginx
      - letsencrypt
      - redis
      - db
    environment:
      - "VIRTUAL_HOST=app.io,www.app.io"
      - "HTTPS_METHOD=redirect"
      - "LETSENCRYPT_HOST=app.io,www.app.io"
      - "LETSENCRYPT_EMAIL=admin@app.io"
    # network_mode: bridge