version: "3"

services:
  openwrt:
    image: p3terx/openwrt-build-env:18.04
    container_name: openwrt
    hostname: Yogurt
    restart: always
    volumes:
      - ./lede:/home/user/openwrt
      - ../..//OpenClash/luci-app-openclash:/home/user/openwrt/package/luci-app-openclash
      - ./config_generate:/home/user/openwrt/package/base-files/files/bin/config_generate
      - ./zzz-default-settings:/home/user/openwrt/package/lean/default-settings/files/zzz-default-settings
    working_dir: /home/user/openwrt
    stdin_open: true
    tty: true

  # build:
  #   build: .
  #   container_name: openwrt
  #   hostname: Yogurt
  #   restart: always
  #   ports:
  #     - "422:22"
  #   volumes:
  #     - ./:/home/user/openwrt
  #   stdin_open: true
  #   tty: true