version: "3"

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx
      DEFAULT_EMAIL: app@lxooo.com

  app:
    image: sungmee/hyperlara
    container_name: ${DOMAIN}
    restart: always
    volumes:
      - ./${DOMAIN}:/var/www
    external_links:
      - nginx
      - letsencrypt
    environment:
      HTTPS_METHOD: noredirect
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN},mirror.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN},mirror.${DOMAIN}

  trojan:
    image: trojangfw/trojan
    container_name: trojan
    restart: always
    external_links:
      - nginx
    ports:
      - 443:443
    volumes:
      - ./trojan.json:/config/config.json
      - ./certs/${DOMAIN}:/certs

  v2ray:
    image: v2ray/official
    container_name: v2ray
    volumes:
      - ./v2ray.json:/etc/v2ray/config.json
      - ./certs/${DOMAIN}:/certs
    ports:
      - 5900:443
    environment:
      DOMAIN: ${DOMAIN}
    command: v2ray -config=/etc/v2ray/config.json
